---
# Inventaire du cluster RKE2
# Remplacez les IPs et noms d'hôtes par vos valeurs réelles

rke2_cluster:
  children:
    rke2_servers:
      hosts:
        server1:
          ansible_host: 192.168.1.10
          ansible_user: root          # sera remplacé par DEPLOY_USER après bootstrap
    rke2_agents:
      hosts:
        agent1:
          ansible_host: 192.168.1.20
          ansible_user: root          # sera remplacé par DEPLOY_USER après bootstrap
        agent2:
          ansible_host: 192.168.1.21
          ansible_user: root
